---

- name: Start and enable firewalld service
  service: name={{ item }} state=started enabled=yes
  with_items:
    - firewalld

- firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - nfs
    - mountd
    - rpc-bind

- name: Enable ports in Firewalld
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - 80/tcp
    - 80/udp
    - 111/tcp
    - 111/udp
    - 443/tcp
    - 443/udp
    - 662/tcp
    - 662/udp    
    - 892/tcp
    - 892/udp
    - 875/tcp
    - 875/udp
    - 2049/tcp
    - 2049/udp
    - 32769/tcp
    - 32769/udp
    - 32803/tcp
    - 32803/udp

- name: Edit /etc/sysconfig/nfs file
  lineinfile: 
    dest: /etc/sysconfig/nfs
    line: '{{ item }}'
  with_items:
    - 'RQUOTAD_PORT=875'
    - 'LOCKD_TCPPORT=32803'
    - 'LOCKD_UDPPORT=32769'
    - 'MOUNTD_PORT=892'
    - 'STATD_PORT=662'


- name: Restart Firewalld service
  service: name={{ item }} state=restarted
  with_items:
    - firewalld
